#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v3
# autospec commit: c1050fe
#
Name     : R-DiceDesign
Version  : 1.10
Release  : 5
URL      : https://cran.r-project.org/src/contrib/DiceDesign_1.10.tar.gz
Source0  : https://cran.r-project.org/src/contrib/DiceDesign_1.10.tar.gz
Summary  : Designs of Computer Experiments
Group    : Development/Tools
License  : GPL-3.0
Requires: R-DiceDesign-lib = %{version}-%{release}
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%package lib
Summary: lib components for the R-DiceDesign package.
Group: Libraries

%description lib
lib components for the R-DiceDesign package.


%prep
%setup -q -n DiceDesign
pushd ..
cp -a DiceDesign buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1702276714

%install
export SOURCE_DATE_EPOCH=1702276714
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/DiceDesign/CITATION
/usr/lib64/R/library/DiceDesign/DESCRIPTION
/usr/lib64/R/library/DiceDesign/INDEX
/usr/lib64/R/library/DiceDesign/Meta/Rd.rds
/usr/lib64/R/library/DiceDesign/Meta/data.rds
/usr/lib64/R/library/DiceDesign/Meta/features.rds
/usr/lib64/R/library/DiceDesign/Meta/hsearch.rds
/usr/lib64/R/library/DiceDesign/Meta/links.rds
/usr/lib64/R/library/DiceDesign/Meta/nsInfo.rds
/usr/lib64/R/library/DiceDesign/Meta/package.rds
/usr/lib64/R/library/DiceDesign/NAMESPACE
/usr/lib64/R/library/DiceDesign/NEWS.md
/usr/lib64/R/library/DiceDesign/R/DiceDesign
/usr/lib64/R/library/DiceDesign/R/DiceDesign.rdb
/usr/lib64/R/library/DiceDesign/R/DiceDesign.rdx
/usr/lib64/R/library/DiceDesign/R/sysdata.rdb
/usr/lib64/R/library/DiceDesign/R/sysdata.rdx
/usr/lib64/R/library/DiceDesign/data/Rdata.rdb
/usr/lib64/R/library/DiceDesign/data/Rdata.rds
/usr/lib64/R/library/DiceDesign/data/Rdata.rdx
/usr/lib64/R/library/DiceDesign/data/datalist
/usr/lib64/R/library/DiceDesign/help/AnIndex
/usr/lib64/R/library/DiceDesign/help/DiceDesign.rdb
/usr/lib64/R/library/DiceDesign/help/DiceDesign.rdx
/usr/lib64/R/library/DiceDesign/help/aliases.rds
/usr/lib64/R/library/DiceDesign/help/paths.rds
/usr/lib64/R/library/DiceDesign/html/00Index.html
/usr/lib64/R/library/DiceDesign/html/R.css

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/DiceDesign/libs/DiceDesign.so
/usr/lib64/R/library/DiceDesign/libs/DiceDesign.so.avx2
/usr/lib64/R/library/DiceDesign/libs/DiceDesign.so.avx512
